import type { Metadata } from "next";

import { Jost } from "next/font/google";

import "./globals.css";

const font = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning>{children}</body>
    </html>
  );
}
