import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const font = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: React.PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </html>
  );
};

export default Layout;
